# Generated by Django 2.1.7 on 2023-12-29 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231229_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 29, 12, 0, 6, 316678)),
        ),
    ]
